# Generated by Django 2.1.7 on 2019-02-27 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=150)),
                ('listingid', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('contactdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('userid', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
    ]
