# Generated by Django 2.1.7 on 2019-02-25 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.PositiveSmallIntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lotsize', models.DecimalField(decimal_places=1, max_digits=4)),
                ('mainimg', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('secimg1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secimg2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secimg3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secimg4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secimg5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('secimg6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('ispublished', models.BooleanField(default=True)),
                ('listdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.Realtor')),
            ],
        ),
    ]
