# Generated by Django 2.1.7 on 2019-02-25 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='photos/realtors')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('ismvp', models.BooleanField(default=False)),
                ('hiredate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
